/home/src/client/use/mysql.py:17: Warning: (1007, "Can't create database 'gsate'; database exists")
  self.cursor.execute('create database if not exists {}'.format(self.table.split('.')[0]))
/home/src/client/use/mysql.py:20: Warning: (1681, 'Integer display width is deprecated and will be removed in a future release.')
  self.cursor.execute('create table if not exists {} {}'.format(self.table, self.get_all(columns)))
/home/src/client/use/mysql.py:20: Warning: (1050, "Table 'person_gsate' already exists")
  self.cursor.execute('create table if not exists {} {}'.format(self.table, self.get_all(columns)))
